const fs = require('fs');
const SITE_NAME = 'HealthCalcs';
const SITE_URL = 'https://alexchalu.github.io/healthcalcs';
const ADSENSE_ID = 'ca-pub-3112605892426625';

const calcs = [
  { slug: 'bmi-calculator', title: 'BMI Calculator', desc: 'Calculate your Body Mass Index (BMI) instantly. Enter height and weight to check if you\'re underweight, normal, overweight, or obese.', keywords: 'bmi calculator, body mass index, bmi check, weight status, healthy weight calculator', category: 'Body' },
  { slug: 'bmr-calculator', title: 'BMR Calculator (Basal Metabolic Rate)', desc: 'Calculate your Basal Metabolic Rate to know how many calories your body burns at rest. Harris-Benedict and Mifflin-St Jeor formulas.', keywords: 'bmr calculator, basal metabolic rate, resting calories, metabolism calculator', category: 'Body' },
  { slug: 'calorie-calculator', title: 'Daily Calorie Calculator', desc: 'Calculate how many calories you need daily based on age, weight, height, and activity level. TDEE calculator included.', keywords: 'calorie calculator, daily calorie needs, tdee calculator, calorie intake, how many calories', category: 'Diet' },
  { slug: 'macro-calculator', title: 'Macro Calculator', desc: 'Calculate your daily macronutrient needs — protein, carbs, and fat. Customize ratios for keto, balanced, high-protein diets.', keywords: 'macro calculator, macronutrient calculator, protein calculator, carbs fat protein, keto macros', category: 'Diet' },
  { slug: 'body-fat-calculator', title: 'Body Fat Percentage Calculator', desc: 'Estimate your body fat percentage using the U.S. Navy method. Enter measurements for accurate results.', keywords: 'body fat calculator, body fat percentage, navy method body fat, fat percentage calculator', category: 'Body' },
  { slug: 'ideal-weight-calculator', title: 'Ideal Weight Calculator', desc: 'Find your ideal body weight based on height using multiple formulas: Devine, Robinson, Miller, and Hamwi.', keywords: 'ideal weight calculator, healthy weight, perfect weight for height, target weight', category: 'Body' },
  { slug: 'pregnancy-due-date', title: 'Pregnancy Due Date Calculator', desc: 'Calculate your estimated due date based on your last menstrual period or conception date. Week-by-week pregnancy timeline.', keywords: 'pregnancy due date calculator, due date calculator, pregnancy calculator, expected delivery date', category: 'Women\'s Health' },
  { slug: 'ovulation-calculator', title: 'Ovulation Calculator & Fertility Calendar', desc: 'Calculate your most fertile days and ovulation date. Track your menstrual cycle for better family planning.', keywords: 'ovulation calculator, fertility calculator, fertile days, ovulation tracker, conception calculator', category: 'Women\'s Health' },
  { slug: 'water-intake-calculator', title: 'Daily Water Intake Calculator', desc: 'Calculate how much water you should drink daily based on weight, activity level, and climate. Stay properly hydrated.', keywords: 'water intake calculator, how much water to drink, daily water needs, hydration calculator', category: 'Diet' },
  { slug: 'sleep-calculator', title: 'Sleep Calculator', desc: 'Calculate the best times to go to sleep or wake up based on sleep cycles. Get optimal rest with 90-minute cycle planning.', keywords: 'sleep calculator, sleep cycle calculator, best time to sleep, wake up time, sleep cycles', category: 'Wellness' },
  { slug: 'heart-rate-zones', title: 'Heart Rate Zone Calculator', desc: 'Calculate your target heart rate zones for fat burning, cardio, and peak performance. Based on max heart rate.', keywords: 'heart rate zone calculator, target heart rate, fat burning zone, cardio zone, max heart rate', category: 'Fitness' },
  { slug: 'one-rep-max', title: 'One Rep Max Calculator (1RM)', desc: 'Calculate your one-rep max for any lift using multiple formulas. Estimate max bench press, squat, deadlift.', keywords: 'one rep max calculator, 1rm calculator, max bench press, max squat, strength calculator', category: 'Fitness' },
  { slug: 'pace-calculator', title: 'Running Pace Calculator', desc: 'Calculate your running pace, finish time, or distance. Perfect for marathon, half marathon, 5K, and 10K training.', keywords: 'pace calculator, running pace, marathon pace, 5k pace calculator, race time calculator', category: 'Fitness' },
  { slug: 'blood-alcohol', title: 'Blood Alcohol Content (BAC) Calculator', desc: 'Estimate your blood alcohol concentration based on drinks, weight, gender, and time. Know when you\'re sober.', keywords: 'bac calculator, blood alcohol calculator, alcohol calculator, drunk calculator, bac level', category: 'Wellness' },
  { slug: 'life-insurance-calculator', title: 'Life Insurance Needs Calculator', desc: 'Calculate how much life insurance coverage you need based on income, debts, dependents, and future expenses.', keywords: 'life insurance calculator, how much life insurance, life insurance needs, coverage calculator, insurance estimate', category: 'Insurance' },
  { slug: 'health-insurance-cost', title: 'Health Insurance Cost Estimator', desc: 'Estimate your health insurance costs based on age, location, plan type, and family size. Compare marketplace options.', keywords: 'health insurance cost calculator, insurance premium estimator, marketplace insurance, health plan cost', category: 'Insurance' },
  { slug: 'protein-calculator', title: 'Protein Intake Calculator', desc: 'Calculate your daily protein requirements based on weight, activity level, and fitness goals. Build muscle effectively.', keywords: 'protein calculator, daily protein needs, protein intake, how much protein, protein for muscle', category: 'Diet' },
  { slug: 'bac-elimination', title: 'Alcohol Elimination Time Calculator', desc: 'Calculate how long it takes to eliminate alcohol from your system. Know when your BAC will reach 0.00%.', keywords: 'alcohol elimination calculator, sober time, when will i be sober, bac elimination, alcohol metabolism', category: 'Wellness' },
  { slug: 'pregnancy-weight-gain', title: 'Pregnancy Weight Gain Calculator', desc: 'Calculate recommended weight gain during pregnancy based on pre-pregnancy BMI. Track healthy weight gain by trimester.', keywords: 'pregnancy weight gain calculator, weight gain pregnancy, healthy pregnancy weight, trimester weight gain', category: 'Women\'s Health' },
  { slug: 'blood-pressure-checker', title: 'Blood Pressure Category Checker', desc: 'Check your blood pressure category: normal, elevated, high Stage 1, high Stage 2, or hypertensive crisis. Know your risk.', keywords: 'blood pressure checker, blood pressure chart, hypertension check, blood pressure categories, bp checker', category: 'Wellness' },
  { slug: 'a1c-calculator', title: 'A1C to Blood Sugar Calculator', desc: 'Convert A1C percentage to average blood sugar (eAG) and vice versa. Essential for diabetes management.', keywords: 'a1c calculator, blood sugar calculator, hba1c, average glucose, diabetes calculator, a1c to blood sugar', category: 'Wellness' },
  { slug: 'disability-insurance', title: 'Disability Insurance Calculator', desc: 'Calculate how much disability insurance you need to replace income if injured or ill. Short-term and long-term coverage.', keywords: 'disability insurance calculator, income replacement, disability coverage, disability insurance needs', category: 'Insurance' },
  { slug: 'waist-hip-ratio', title: 'Waist-to-Hip Ratio Calculator', desc: 'Calculate your waist-to-hip ratio to assess health risks. A key indicator of cardiovascular and metabolic health.', keywords: 'waist hip ratio, whr calculator, waist to hip, health risk calculator, body shape calculator', category: 'Body' },
  { slug: 'smoking-cost', title: 'Smoking Cost Calculator', desc: 'Calculate how much money you spend on smoking per week, month, and year. See the financial impact of quitting.', keywords: 'smoking cost calculator, cost of smoking, cigarette cost, money spent on smoking, quit smoking savings', category: 'Wellness' },
];

function generateCalcPage(calc) {
  const related = calcs.filter(c => c.slug !== calc.slug && c.category === calc.category).slice(0, 3);
  const otherRelated = calcs.filter(c => c.slug !== calc.slug && c.category !== calc.category).slice(0, 3);
  const allRelated = [...related, ...otherRelated].slice(0, 6);
  
  return \`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>\${calc.title} — Free Online | \${SITE_NAME}</title>
<meta name="description" content="\${calc.desc}">
<meta name="keywords" content="\${calc.keywords}">
<link rel="canonical" href="\${SITE_URL}/\${calc.slug}.html">
<meta property="og:title" content="\${calc.title}">
<meta property="og:description" content="\${calc.desc}">
<meta property="og:url" content="\${SITE_URL}/\${calc.slug}.html">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=\${ADSENSE_ID}" crossorigin="anonymous"></script>
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"WebApplication","name":"\${calc.title}","url":"\${SITE_URL}/\${calc.slug}.html","description":"\${calc.desc}","applicationCategory":"HealthApplication","operatingSystem":"All","offers":{"@type":"Offer","price":"0","priceCurrency":"USD"}}
</script>
<style>
*{margin:0;padding:0;box-sizing:border-box}
:root{--bg:#0c1222;--surface:#162032;--border:#1e3a5f;--text:#e2e8f0;--muted:#8899aa;--accent:#10b981;--accent2:#06b6d4;--danger:#ef4444;--warn:#f59e0b}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:var(--bg);color:var(--text);line-height:1.6}
.container{max-width:800px;margin:0 auto;padding:20px}
header{text-align:center;padding:30px 0;border-bottom:1px solid var(--border)}
header h1{font-size:1.9em;margin-bottom:8px;background:linear-gradient(135deg,var(--accent),var(--accent2));-webkit-background-clip:text;-webkit-text-fill-color:transparent}
header p{color:var(--muted);font-size:1.05em}
.logo-link{text-decoration:none;color:var(--muted);font-size:0.9em;display:inline-block;margin-bottom:10px}
.calc-area{background:var(--surface);border-radius:12px;padding:24px;margin:24px 0;border:1px solid var(--border)}
label{display:block;color:var(--muted);font-size:0.9em;margin:12px 0 4px}
input,select{width:100%;padding:12px;background:var(--bg);border:1px solid var(--border);border-radius:8px;color:var(--text);font-size:15px}
.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}
button{padding:14px 28px;background:var(--accent);color:#fff;border:none;border-radius:8px;cursor:pointer;font-size:16px;font-weight:600;width:100%;margin:16px 0;transition:all .2s}
button:hover{opacity:0.9;transform:translateY(-1px)}
.result{background:var(--bg);border-radius:12px;padding:20px;margin:16px 0;border:1px solid var(--border);text-align:center}
.result .value{font-size:2.5em;font-weight:700;background:linear-gradient(135deg,var(--accent),var(--accent2));-webkit-background-clip:text;-webkit-text-fill-color:transparent}
.result .label{color:var(--muted);font-size:0.9em;margin-top:4px}
.result-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px;margin:16px 0}
.result-card{background:var(--bg);border:1px solid var(--border);border-radius:8px;padding:14px;text-align:center}
.result-card .num{font-size:1.4em;font-weight:700;color:var(--accent)}
.result-card .lbl{font-size:0.8em;color:var(--muted);margin-top:4px}
.info-box{background:rgba(16,185,129,0.1);border:1px solid rgba(16,185,129,0.3);border-radius:8px;padding:16px;margin:16px 0;font-size:0.95em;line-height:1.7}
.warn-box{background:rgba(245,158,11,0.1);border:1px solid rgba(245,158,11,0.3);border-radius:8px;padding:16px;margin:16px 0}
.danger-box{background:rgba(239,68,68,0.1);border:1px solid rgba(239,68,68,0.3);border-radius:8px;padding:16px;margin:16px 0}
.ad-slot{margin:20px 0;min-height:90px;text-align:center}
.related{margin:40px 0}
.related h3{margin-bottom:16px;color:var(--muted)}
.related-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:12px}
.related-grid a{display:block;padding:14px;background:var(--surface);border:1px solid var(--border);border-radius:8px;text-decoration:none;color:var(--text);transition:all .2s}
.related-grid a:hover{border-color:var(--accent);transform:translateY(-2px)}
.disclaimer{color:var(--muted);font-size:0.8em;text-align:center;margin:20px 0;padding:16px;border:1px solid var(--border);border-radius:8px}
footer{text-align:center;padding:40px 0;color:var(--muted);border-top:1px solid var(--border);margin-top:40px}
footer a{color:var(--accent);text-decoration:none}
@media(max-width:600px){.container{padding:12px}header h1{font-size:1.5em}.row{grid-template-columns:1fr}.result .value{font-size:2em}}
</style>
</head>
<body>
<div class="container">
<header>
<a href="index.html" class="logo-link">← \${SITE_NAME}</a>
<h1>\${calc.title}</h1>
<p>\${calc.desc}</p>
</header>
<div class="ad-slot"><ins class="adsbygoogle" style="display:block" data-ad-client="\${ADSENSE_ID}" data-ad-slot="auto" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div>
<div class="calc-area" id="calc"></div>
<div class="ad-slot"><ins class="adsbygoogle" style="display:block" data-ad-client="\${ADSENSE_ID}" data-ad-slot="auto" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div>
<div class="disclaimer">⚠️ This calculator is for informational purposes only and should not replace professional medical advice. Always consult with a healthcare provider for medical decisions.</div>
<div class="related">
<h3>Related Calculators</h3>
<div class="related-grid">
\${allRelated.map(r => '<a href="'+r.slug+'.html">'+r.title+'</a>').join('\\n')}
</div>
</div>
<div class="ad-slot"><ins class="adsbygoogle" style="display:block" data-ad-client="\${ADSENSE_ID}" data-ad-slot="auto" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div>
<footer>
<p><a href="index.html">\${SITE_NAME}</a> — Free Health & Wellness Calculators</p>
<p style="margin-top:8px"><a href="https://alexchalu.github.io/toolpulse/">ToolPulse</a> · <a href="https://alexchalu.github.io/smartcalc/">SmartCalc</a> · <a href="https://alexchalu.github.io/writefast/">WriteFast</a></p>
</footer>
</div>
<script>\${getCalcScript(calc)}</script>
</body>
</html>\`;
}

function getCalcScript(calc) {
  const scripts = {
'bmi-calculator': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Height</label><div class="row"><div><input type="number" id="feet" placeholder="Feet" min="1" max="8"></div><div><input type="number" id="inches" placeholder="Inches" min="0" max="11"></div></div></div><div><label>Weight (lbs)</label><input type="number" id="weight" placeholder="e.g. 160" min="50" max="700"></div></div><button onclick="calc()">Calculate BMI</button><div id="result"></div>';function calc(){const f=+document.getElementById('feet').value;const i=+document.getElementById('inches').value;const w=+document.getElementById('weight').value;if(!f||!w)return;const h=(f*12+i);const bmi=(w/(h*h)*703).toFixed(1);let cat,col;if(bmi<18.5){cat='Underweight';col='var(--accent2)'}else if(bmi<25){cat='Normal Weight';col='var(--accent)'}else if(bmi<30){cat='Overweight';col='var(--warn)'}else{cat='Obese';col='var(--danger)'}document.getElementById('result').innerHTML='<div class="result"><div class="value" style="-webkit-text-fill-color:'+col+'">'+bmi+'</div><div class="label">'+cat+'</div></div><div class="info-box"><strong>BMI Categories:</strong><br>Underweight: Below 18.5<br>Normal: 18.5 – 24.9<br>Overweight: 25.0 – 29.9<br>Obese: 30.0 and above</div>'}\`,
'bmr-calculator': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Age</label><input type="number" id="age" placeholder="Years" min="10" max="100"></div><div><label>Gender</label><select id="gender"><option value="male">Male</option><option value="female">Female</option></select></div></div><div class="row"><div><label>Height (inches)</label><input type="number" id="height" placeholder="e.g. 70" min="36" max="96"></div><div><label>Weight (lbs)</label><input type="number" id="weight" placeholder="e.g. 160" min="50" max="700"></div></div><label>Activity Level</label><select id="activity"><option value="1.2">Sedentary (little/no exercise)</option><option value="1.375">Light (1-3 days/week)</option><option value="1.55">Moderate (3-5 days/week)</option><option value="1.725">Active (6-7 days/week)</option><option value="1.9">Very Active (2x/day)</option></select><button onclick="calc()">Calculate BMR & TDEE</button><div id="result"></div>';function calc(){const a=+document.getElementById('age').value;const g=document.getElementById('gender').value;const h=+document.getElementById('height').value*2.54;const w=+document.getElementById('weight').value*0.453592;const act=+document.getElementById('activity').value;if(!a||!h||!w)return;let bmr;if(g==='male')bmr=10*w+6.25*h-5*a+5;else bmr=10*w+6.25*h-5*a-161;const tdee=bmr*act;document.getElementById('result').innerHTML='<div class="result-grid"><div class="result-card"><div class="num">'+Math.round(bmr)+'</div><div class="lbl">BMR (cal/day)</div></div><div class="result-card"><div class="num">'+Math.round(tdee)+'</div><div class="lbl">TDEE (cal/day)</div></div><div class="result-card"><div class="num">'+Math.round(tdee-500)+'</div><div class="lbl">Lose Weight</div></div><div class="result-card"><div class="num">'+Math.round(tdee+500)+'</div><div class="lbl">Gain Weight</div></div></div><div class="info-box">Your BMR is '+Math.round(bmr)+' calories — this is what your body burns at rest.<br>Your TDEE is '+Math.round(tdee)+' calories — this is your total daily expenditure including activity.<br>To lose ~1 lb/week, eat '+Math.round(tdee-500)+' cal/day. To gain, eat '+Math.round(tdee+500)+' cal/day.</div>'}\`,
'calorie-calculator': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Age</label><input type="number" id="age" placeholder="Years"></div><div><label>Gender</label><select id="gender"><option value="male">Male</option><option value="female">Female</option></select></div></div><div class="row"><div><label>Height (inches)</label><input type="number" id="height" placeholder="e.g. 70"></div><div><label>Weight (lbs)</label><input type="number" id="weight" placeholder="e.g. 160"></div></div><label>Activity Level</label><select id="activity"><option value="1.2">Sedentary</option><option value="1.375">Lightly Active</option><option value="1.55">Moderately Active</option><option value="1.725">Very Active</option><option value="1.9">Extra Active</option></select><label>Goal</label><select id="goal"><option value="lose2">Lose 2 lbs/week</option><option value="lose1">Lose 1 lb/week</option><option value="maintain">Maintain Weight</option><option value="gain1">Gain 1 lb/week</option><option value="gain2">Gain 2 lbs/week</option></select><button onclick="calc()">Calculate Calories</button><div id="result"></div>';function calc(){const a=+document.getElementById('age').value;const g=document.getElementById('gender').value;const h=+document.getElementById('height').value*2.54;const w=+document.getElementById('weight').value*0.453592;const act=+document.getElementById('activity').value;const goal=document.getElementById('goal').value;if(!a||!h||!w)return;let bmr;if(g==='male')bmr=10*w+6.25*h-5*a+5;else bmr=10*w+6.25*h-5*a-161;const tdee=bmr*act;const adj={lose2:-1000,lose1:-500,maintain:0,gain1:500,gain2:1000};const target=Math.round(tdee+adj[goal]);document.getElementById('result').innerHTML='<div class="result"><div class="value">'+target+'</div><div class="label">Calories Per Day</div></div><div class="result-grid"><div class="result-card"><div class="num">'+Math.round(target*0.3/4)+'g</div><div class="lbl">Protein</div></div><div class="result-card"><div class="num">'+Math.round(target*0.4/4)+'g</div><div class="lbl">Carbs</div></div><div class="result-card"><div class="num">'+Math.round(target*0.3/9)+'g</div><div class="lbl">Fat</div></div></div>'}\`,
'macro-calculator': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Daily Calories</label><input type="number" id="calories" placeholder="e.g. 2000"></div><div><label>Diet Plan</label><select id="plan" onchange="updateRatios()"><option value="balanced">Balanced (30/40/30)</option><option value="lowcarb">Low Carb (40/20/40)</option><option value="keto">Keto (30/5/65)</option><option value="highprotein">High Protein (40/30/30)</option><option value="custom">Custom</option></select></div></div><div class="row"><div><label>Protein %</label><input type="number" id="protein" value="30" min="5" max="60"></div><div><label>Carbs %</label><input type="number" id="carbs" value="40" min="5" max="70"></div><div><label>Fat %</label><input type="number" id="fat" value="30" min="10" max="80"></div></div><button onclick="calc()">Calculate Macros</button><div id="result"></div>';function updateRatios(){const plan=document.getElementById('plan').value;const r={balanced:[30,40,30],lowcarb:[40,20,40],keto:[30,5,65],highprotein:[40,30,30],custom:[30,40,30]};document.getElementById('protein').value=r[plan][0];document.getElementById('carbs').value=r[plan][1];document.getElementById('fat').value=r[plan][2]}function calc(){const cal=+document.getElementById('calories').value;const p=+document.getElementById('protein').value;const cb=+document.getElementById('carbs').value;const f=+document.getElementById('fat').value;if(!cal)return;if(Math.abs(p+cb+f-100)>1){alert('Percentages must add up to 100%');return}document.getElementById('result').innerHTML='<div class="result-grid"><div class="result-card"><div class="num">'+Math.round(cal*p/100/4)+'g</div><div class="lbl">Protein ('+p+'%)</div></div><div class="result-card"><div class="num">'+Math.round(cal*cb/100/4)+'g</div><div class="lbl">Carbs ('+cb+'%)</div></div><div class="result-card"><div class="num">'+Math.round(cal*f/100/9)+'g</div><div class="lbl">Fat ('+f+'%)</div></div></div><div class="info-box">Based on '+cal+' calories/day:<br>• Protein: '+Math.round(cal*p/100/4)+'g ('+Math.round(cal*p/100)+' cal)<br>• Carbs: '+Math.round(cal*cb/100/4)+'g ('+Math.round(cal*cb/100)+' cal)<br>• Fat: '+Math.round(cal*f/100/9)+'g ('+Math.round(cal*f/100)+' cal)</div>'}\`,
'body-fat-calculator': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Gender</label><select id="gender"><option value="male">Male</option><option value="female">Female</option></select></div><div><label>Height (inches)</label><input type="number" id="height" placeholder="e.g. 70"></div></div><div class="row"><div><label>Waist (inches)</label><input type="number" id="waist" placeholder="At navel" step="0.5"></div><div><label>Neck (inches)</label><input type="number" id="neck" placeholder="Below larynx" step="0.5"></div></div><div id="hipRow"><label>Hip (inches) — Women only</label><input type="number" id="hip" placeholder="Widest point" step="0.5"></div><button onclick="calc()">Calculate Body Fat</button><div id="result"></div>';document.getElementById('gender').onchange=function(){document.getElementById('hipRow').style.display=this.value==='female'?'block':'none'};function calc(){const g=document.getElementById('gender').value;const h=+document.getElementById('height').value;const w=+document.getElementById('waist').value;const n=+document.getElementById('neck').value;const hip=+document.getElementById('hip').value;if(!h||!w||!n)return;let bf;if(g==='male')bf=86.010*Math.log10(w-n)-70.041*Math.log10(h)+36.76;else{if(!hip)return;bf=163.205*Math.log10(w+hip-n)-97.684*Math.log10(h)-78.387}bf=bf.toFixed(1);let cat;if(g==='male'){if(bf<6)cat='Essential Fat';else if(bf<14)cat='Athletes';else if(bf<18)cat='Fitness';else if(bf<25)cat='Average';else cat='Obese'}else{if(bf<14)cat='Essential Fat';else if(bf<21)cat='Athletes';else if(bf<25)cat='Fitness';else if(bf<32)cat='Average';else cat='Obese'}document.getElementById('result').innerHTML='<div class="result"><div class="value">'+bf+'%</div><div class="label">Body Fat — '+cat+'</div></div>'}\`,
'ideal-weight-calculator': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Height</label><div class="row"><div><input type="number" id="feet" placeholder="Feet" min="4" max="7"></div><div><input type="number" id="inches" placeholder="Inches" min="0" max="11"></div></div></div><div><label>Gender</label><select id="gender"><option value="male">Male</option><option value="female">Female</option></select></div></div><button onclick="calc()">Calculate</button><div id="result"></div>';function calc(){const f=+document.getElementById('feet').value;const i=+document.getElementById('inches').value;const g=document.getElementById('gender').value;if(!f)return;const h=f*12+i;const over=h-60;if(g==='male'){var devine=50+2.3*over;var robinson=52+1.9*over;var miller=56.2+1.41*over;var hamwi=48+2.7*over}else{var devine=45.5+2.3*over;var robinson=49+1.7*over;var miller=53.1+1.36*over;var hamwi=45.5+2.2*over}const avg=((devine+robinson+miller+hamwi)/4).toFixed(0);document.getElementById('result').innerHTML='<div class="result"><div class="value">'+avg+' lbs</div><div class="label">Average Ideal Weight</div></div><div class="result-grid"><div class="result-card"><div class="num">'+(devine*2.205).toFixed(0)+' lbs</div><div class="lbl">Devine Formula</div></div><div class="result-card"><div class="num">'+(robinson*2.205).toFixed(0)+' lbs</div><div class="lbl">Robinson</div></div><div class="result-card"><div class="num">'+(miller*2.205).toFixed(0)+' lbs</div><div class="lbl">Miller</div></div><div class="result-card"><div class="num">'+(hamwi*2.205).toFixed(0)+' lbs</div><div class="lbl">Hamwi</div></div></div>'}\`,
'pregnancy-due-date': \`const c=document.getElementById('calc');c.innerHTML='<label>First Day of Last Menstrual Period</label><input type="date" id="lmp"><button onclick="calc()">Calculate Due Date</button><div id="result"></div>';function calc(){const lmp=new Date(document.getElementById('lmp').value);if(isNaN(lmp))return;const due=new Date(lmp);due.setDate(due.getDate()+280);const today=new Date();const daysPreg=Math.floor((today-lmp)/(1000*60*60*24));const weeksPreg=Math.floor(daysPreg/7);const daysExtra=daysPreg%7;const daysLeft=Math.max(0,Math.floor((due-today)/(1000*60*60*24)));const trimester=weeksPreg<13?'First':weeksPreg<27?'Second':'Third';document.getElementById('result').innerHTML='<div class="result"><div class="value">'+due.toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})+'</div><div class="label">Estimated Due Date</div></div><div class="result-grid"><div class="result-card"><div class="num">'+weeksPreg+'w '+daysExtra+'d</div><div class="lbl">Current Week</div></div><div class="result-card"><div class="num">'+daysLeft+'</div><div class="lbl">Days Remaining</div></div><div class="result-card"><div class="num">'+trimester+'</div><div class="lbl">Trimester</div></div></div>'}\`,
'ovulation-calculator': \`const c=document.getElementById('calc');c.innerHTML='<label>First Day of Last Period</label><input type="date" id="lmp"><div class="row"><div><label>Cycle Length (days)</label><input type="number" id="cycle" value="28" min="21" max="45"></div><div><label>Luteal Phase (days)</label><input type="number" id="luteal" value="14" min="10" max="16"></div></div><button onclick="calc()">Calculate Fertile Window</button><div id="result"></div>';function calc(){const lmp=new Date(document.getElementById('lmp').value);const cycle=+document.getElementById('cycle').value;const luteal=+document.getElementById('luteal').value;if(isNaN(lmp)||!cycle)return;const ovDay=cycle-luteal;const nextPeriod=new Date(lmp);nextPeriod.setDate(nextPeriod.getDate()+cycle);const ovulation=new Date(lmp);ovulation.setDate(ovulation.getDate()+ovDay);const fertileStart=new Date(ovulation);fertileStart.setDate(fertileStart.getDate()-5);const fertileEnd=new Date(ovulation);fertileEnd.setDate(fertileEnd.getDate()+1);const fmt=d=>d.toLocaleDateString('en-US',{month:'short',day:'numeric'});document.getElementById('result').innerHTML='<div class="result"><div class="value">'+fmt(ovulation)+'</div><div class="label">Estimated Ovulation Date</div></div><div class="result-grid"><div class="result-card"><div class="num">'+fmt(fertileStart)+'</div><div class="lbl">Fertile Window Start</div></div><div class="result-card"><div class="num">'+fmt(fertileEnd)+'</div><div class="lbl">Fertile Window End</div></div><div class="result-card"><div class="num">'+fmt(nextPeriod)+'</div><div class="lbl">Next Period</div></div></div><div class="info-box">Your fertile window is '+fmt(fertileStart)+' to '+fmt(fertileEnd)+'. The highest chance of conception is 1-2 days before ovulation.</div>'}\`,
'water-intake-calculator': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Weight (lbs)</label><input type="number" id="weight" placeholder="e.g. 160"></div><div><label>Activity Level</label><select id="activity"><option value="0">Sedentary</option><option value="12">Light Exercise</option><option value="24">Moderate Exercise</option><option value="36">Intense Exercise</option></select></div></div><label>Climate</label><select id="climate"><option value="0">Temperate</option><option value="16">Hot/Humid</option><option value="8">Dry/Arid</option></select><button onclick="calc()">Calculate Water Intake</button><div id="result"></div>';function calc(){const w=+document.getElementById('weight').value;const a=+document.getElementById('activity').value;const cl=+document.getElementById('climate').value;if(!w)return;const base=w*0.5;const total=base+a+cl;const liters=(total*0.0296).toFixed(1);const cups=Math.round(total/8);document.getElementById('result').innerHTML='<div class="result"><div class="value">'+Math.round(total)+' oz</div><div class="label">Daily Water Intake</div></div><div class="result-grid"><div class="result-card"><div class="num">'+liters+'L</div><div class="lbl">Liters</div></div><div class="result-card"><div class="num">'+cups+'</div><div class="lbl">Cups (8oz)</div></div><div class="result-card"><div class="num">'+Math.round(total/16.9)+'</div><div class="lbl">Water Bottles</div></div></div>'}\`,
'sleep-calculator': \`const c=document.getElementById('calc');c.innerHTML='<label>I want to:</label><select id="mode" onchange="toggleMode()"><option value="wake">Wake up at a specific time</option><option value="sleep">Fall asleep now</option></select><div id="timeInput"><label>Wake-up Time</label><input type="time" id="wakeTime" value="07:00"></div><button onclick="calc()">Calculate Sleep Times</button><div id="result"></div>';function toggleMode(){document.getElementById('timeInput').style.display=document.getElementById('mode').value==='wake'?'block':'none'}function calc(){const mode=document.getElementById('mode').value;const cycleMins=90;const fallAsleep=15;let html='';if(mode==='wake'){const wake=document.getElementById('wakeTime').value;const[h,m]=wake.split(':').map(Number);const wakeMin=h*60+m;html='<div class="info-box"><strong>To wake at '+wake+', go to sleep at:</strong></div><div class="result-grid">';for(let cycles=6;cycles>=3;cycles--){const sleepMin=((wakeMin-cycles*cycleMins-fallAsleep)%1440+1440)%1440;const sh=Math.floor(sleepMin/60);const sm=sleepMin%60;const time=(sh>12?sh-12:sh||12)+':'+(sm<10?'0':'')+sm+(sh>=12?' PM':' AM');html+='<div class="result-card"><div class="num">'+time+'</div><div class="lbl">'+cycles+' cycles ('+cycles*1.5+'h)</div></div>'}html+='</div>'}else{const now=new Date();html='<div class="info-box"><strong>If you fall asleep now, wake up at:</strong></div><div class="result-grid">';for(let cycles=3;cycles<=6;cycles++){const wake=new Date(now.getTime()+(fallAsleep+cycles*cycleMins)*60000);const time=wake.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});html+='<div class="result-card"><div class="num">'+time+'</div><div class="lbl">'+cycles+' cycles ('+cycles*1.5+'h)</div></div>'}html+='</div>'}html+='<div class="info-box">💡 Each sleep cycle is ~90 minutes. Waking between cycles (not during) helps you feel refreshed. Most adults need 4-6 cycles (6-9 hours).</div>';document.getElementById('result').innerHTML=html}\`,
'heart-rate-zones': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Age</label><input type="number" id="age" placeholder="Years" min="10" max="100"></div><div><label>Resting Heart Rate (optional)</label><input type="number" id="rhr" placeholder="BPM" min="30" max="120"></div></div><button onclick="calc()">Calculate Zones</button><div id="result"></div>';function calc(){const age=+document.getElementById('age').value;const rhr=+document.getElementById('rhr').value||70;if(!age)return;const mhr=220-age;const zones=[{name:'Zone 1: Recovery',pct:[50,60],color:'var(--accent2)'},{name:'Zone 2: Fat Burn',pct:[60,70],color:'var(--accent)'},{name:'Zone 3: Aerobic',pct:[70,80],color:'var(--warn)'},{name:'Zone 4: Anaerobic',pct:[80,90],color:'#f97316'},{name:'Zone 5: Max Effort',pct:[90,100],color:'var(--danger)'}];document.getElementById('result').innerHTML='<div class="result"><div class="value">'+mhr+'</div><div class="label">Max Heart Rate (BPM)</div></div><div class="result-grid">'+zones.map(z=>'<div class="result-card"><div class="num" style="color:'+z.color+'">'+Math.round(mhr*z.pct[0]/100)+'-'+Math.round(mhr*z.pct[1]/100)+'</div><div class="lbl">'+z.name+'</div></div>').join('')+'</div>'}\`,
'one-rep-max': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Weight Lifted (lbs)</label><input type="number" id="weight" placeholder="e.g. 225"></div><div><label>Reps Performed</label><input type="number" id="reps" placeholder="e.g. 5" min="1" max="30"></div></div><button onclick="calc()">Calculate 1RM</button><div id="result"></div>';function calc(){const w=+document.getElementById('weight').value;const r=+document.getElementById('reps').value;if(!w||!r)return;const brzycki=w*(36/(37-r));const epley=w*(1+r/30);const avg=((brzycki+epley)/2).toFixed(0);document.getElementById('result').innerHTML='<div class="result"><div class="value">'+avg+' lbs</div><div class="label">Estimated One Rep Max</div></div><div class="result-grid">'+[{p:100,l:'1RM'},{p:95,l:'2 reps'},{p:90,l:'4 reps'},{p:85,l:'6 reps'},{p:80,l:'8 reps'},{p:75,l:'10 reps'},{p:70,l:'12 reps'},{p:65,l:'15 reps'}].map(x=>'<div class="result-card"><div class="num">'+Math.round(avg*x.p/100)+'</div><div class="lbl">'+x.p+'% ('+x.l+')</div></div>').join('')+'</div>'}\`,
'pace-calculator': \`const c=document.getElementById('calc');c.innerHTML='<label>Distance</label><select id="dist"><option value="3.1">5K</option><option value="6.2">10K</option><option value="13.1">Half Marathon</option><option value="26.2">Marathon</option><option value="custom">Custom (miles)</option></select><input type="number" id="customDist" placeholder="Miles" style="display:none"><label>Finish Time</label><div class="row"><div><input type="number" id="hours" placeholder="Hours" min="0"></div><div><input type="number" id="minutes" placeholder="Minutes" min="0" max="59"></div><div><input type="number" id="seconds" placeholder="Seconds" min="0" max="59"></div></div><button onclick="calc()">Calculate Pace</button><div id="result"></div>';document.getElementById('dist').onchange=function(){document.getElementById('customDist').style.display=this.value==='custom'?'block':'none'};function calc(){let d=+document.getElementById('dist').value;if(isNaN(d))d=+document.getElementById('customDist').value;const h=+document.getElementById('hours').value||0;const m=+document.getElementById('minutes').value||0;const s=+document.getElementById('seconds').value||0;if(!d)return;const totalSec=h*3600+m*60+s;if(!totalSec)return;const paceSecPerMile=totalSec/d;const pm=Math.floor(paceSecPerMile/60);const ps=Math.round(paceSecPerMile%60);const mph=(d/(totalSec/3600)).toFixed(1);const kph=(d*1.60934/(totalSec/3600)).toFixed(1);document.getElementById('result').innerHTML='<div class="result"><div class="value">'+pm+':'+String(ps).padStart(2,'0')+'</div><div class="label">Pace (min/mile)</div></div><div class="result-grid"><div class="result-card"><div class="num">'+mph+'</div><div class="lbl">MPH</div></div><div class="result-card"><div class="num">'+kph+'</div><div class="lbl">KPH</div></div><div class="result-card"><div class="num">'+d.toFixed(1)+'</div><div class="lbl">Miles</div></div></div>'}\`,
'blood-alcohol': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Gender</label><select id="gender"><option value="male">Male</option><option value="female">Female</option></select></div><div><label>Weight (lbs)</label><input type="number" id="weight" placeholder="e.g. 160"></div></div><div class="row"><div><label>Standard Drinks</label><input type="number" id="drinks" placeholder="e.g. 3" min="0" step="0.5"></div><div><label>Hours Drinking</label><input type="number" id="hours" placeholder="e.g. 2" min="0" step="0.5"></div></div><button onclick="calc()">Calculate BAC</button><div id="result"></div>';function calc(){const g=document.getElementById('gender').value;const w=+document.getElementById('weight').value;const d=+document.getElementById('drinks').value;const h=+document.getElementById('hours').value;if(!w||d===undefined)return;const r=g==='male'?0.73:0.66;const bac=Math.max(0,((d*0.6*5.14)/(w*r))-0.015*h).toFixed(3);let status,col;if(bac<0.02){status='Sober';col='var(--accent)'}else if(bac<0.06){status='Buzzed';col='var(--warn)'}else if(bac<0.08){status='Impaired';col='#f97316'}else if(bac<0.15){status='Legally Drunk';col='var(--danger)'}else{status='DANGEROUS';col='var(--danger)'}const soberHours=bac>0?Math.ceil(bac/0.015):0;document.getElementById('result').innerHTML='<div class="result"><div class="value" style="-webkit-text-fill-color:'+col+'">'+bac+'%</div><div class="label">'+status+'</div></div><div class="result-grid"><div class="result-card"><div class="num">'+soberHours+'h</div><div class="lbl">Time to Sober</div></div><div class="result-card"><div class="num">'+(bac>=0.08?'NO':'Yes')+'</div><div class="lbl">Legal to Drive?</div></div></div>'+(bac>=0.08?'<div class="danger-box">⚠️ Your BAC is above the legal limit of 0.08%. DO NOT DRIVE.</div>':'')}\`,
'life-insurance-calculator': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Annual Income</label><input type="number" id="income" placeholder="e.g. 75000"></div><div><label>Years to Replace Income</label><input type="number" id="years" value="10" min="1" max="40"></div></div><div class="row"><div><label>Outstanding Debts ($)</label><input type="number" id="debts" placeholder="Mortgage, loans..." value="0"></div><div><label>Future Education Costs ($)</label><input type="number" id="education" placeholder="College fund..." value="0"></div></div><div class="row"><div><label>Final Expenses ($)</label><input type="number" id="final" value="15000"></div><div><label>Existing Coverage ($)</label><input type="number" id="existing" value="0"></div></div><button onclick="calc()">Calculate Coverage Needed</button><div id="result"></div>';function calc(){const inc=+document.getElementById('income').value||0;const yrs=+document.getElementById('years').value||10;const debts=+document.getElementById('debts').value||0;const edu=+document.getElementById('education').value||0;const fin=+document.getElementById('final').value||15000;const exist=+document.getElementById('existing').value||0;const incomeNeed=inc*yrs;const total=incomeNeed+debts+edu+fin;const need=Math.max(0,total-exist);const fmt=n=>'$'+n.toLocaleString();document.getElementById('result').innerHTML='<div class="result"><div class="value">'+fmt(need)+'</div><div class="label">Recommended Coverage</div></div><div class="result-grid"><div class="result-card"><div class="num">'+fmt(incomeNeed)+'</div><div class="lbl">Income Replacement</div></div><div class="result-card"><div class="num">'+fmt(debts)+'</div><div class="lbl">Debt Coverage</div></div><div class="result-card"><div class="num">'+fmt(edu)+'</div><div class="lbl">Education Fund</div></div><div class="result-card"><div class="num">'+fmt(fin)+'</div><div class="lbl">Final Expenses</div></div></div><div class="info-box">The DIME method recommends: Debts + Income replacement + Mortgage + Education costs. A common rule of thumb is 10-15x your annual income.</div>'}\`,
'health-insurance-cost': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Age</label><input type="number" id="age" placeholder="e.g. 35" min="18" max="64"></div><div><label>Plan Type</label><select id="plan"><option value="bronze">Bronze (60/40)</option><option value="silver">Silver (70/30)</option><option value="gold">Gold (80/20)</option><option value="platinum">Platinum (90/10)</option></select></div></div><div class="row"><div><label>Coverage</label><select id="coverage"><option value="1">Individual</option><option value="1.8">Couple</option><option value="2.3">Family</option></select></div><div><label>Annual Income ($)</label><input type="number" id="income" placeholder="For subsidy estimate"></div></div><button onclick="calc()">Estimate Costs</button><div id="result"></div>';function calc(){const age=+document.getElementById('age').value;const plan=document.getElementById('plan').value;const cov=+document.getElementById('coverage').value;const inc=+document.getElementById('income').value||50000;if(!age)return;const basePremium={bronze:350,silver:450,gold:550,platinum:650};let premium=basePremium[plan];const ageFactor=age<21?0.635:age<30?1.0:age<40?1.135:age<50?1.325:age<60?1.786:2.714;premium=Math.round(premium*ageFactor*cov);const deductible={bronze:7500,silver:4500,gold:1500,platinum:500};const oop={bronze:9100,silver:7800,gold:6000,platinum:3000};const subsidy=inc<60000?Math.round(premium*0.3):0;const fmt=n=>'$'+n.toLocaleString();document.getElementById('result').innerHTML='<div class="result"><div class="value">'+fmt(premium-subsidy)+'/mo</div><div class="label">Estimated Monthly Premium</div></div><div class="result-grid"><div class="result-card"><div class="num">'+fmt(deductible[plan])+'</div><div class="lbl">Deductible</div></div><div class="result-card"><div class="num">'+fmt(oop[plan])+'</div><div class="lbl">Max Out-of-Pocket</div></div><div class="result-card"><div class="num">'+fmt((premium-subsidy)*12)+'</div><div class="lbl">Annual Premium</div></div><div class="result-card"><div class="num">'+fmt(subsidy>0?subsidy:0)+'/mo</div><div class="lbl">Est. Subsidy</div></div></div>'}\`,
  };
  // Simple fallback for remaining calculators
  const simpleCalcs = {
'protein-calculator': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Weight (lbs)</label><input type="number" id="weight" placeholder="e.g. 160"></div><div><label>Goal</label><select id="goal"><option value="0.36">Sedentary (RDA minimum)</option><option value="0.5">General Fitness</option><option value="0.7">Muscle Building</option><option value="0.9">Intense Training</option><option value="1.0">Bodybuilding/Athlete</option></select></div></div><button onclick="calc()">Calculate Protein Needs</button><div id="result"></div>';function calc(){const w=+document.getElementById('weight').value;const g=+document.getElementById('goal').value;if(!w)return;const protein=Math.round(w*g);document.getElementById('result').innerHTML='<div class="result"><div class="value">'+protein+'g</div><div class="label">Daily Protein Target</div></div><div class="info-box">Based on '+w+' lbs body weight × '+g+'g per pound = '+protein+'g protein daily.<br><br>• Chicken breast (6oz): ~38g protein<br>• Eggs (2 large): ~12g<br>• Greek yogurt (1 cup): ~17g<br>• Whey protein shake: ~25g</div>'}\`,
'bac-elimination': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Current BAC (%)</label><input type="number" id="bac" placeholder="e.g. 0.08" step="0.01" min="0" max="0.5"></div><div><label>Or: Standard Drinks</label><input type="number" id="drinks" placeholder="e.g. 4" min="0"></div></div><div class="row"><div><label>Weight (lbs)</label><input type="number" id="weight" placeholder="e.g. 160"></div><div><label>Gender</label><select id="gender"><option value="male">Male</option><option value="female">Female</option></select></div></div><button onclick="calc()">Calculate Sober Time</button><div id="result"></div>';function calc(){let bac=+document.getElementById('bac').value;const drinks=+document.getElementById('drinks').value;const w=+document.getElementById('weight').value;const g=document.getElementById('gender').value;if(!bac&&drinks&&w){const r=g==='male'?0.73:0.66;bac=(drinks*0.6*5.14)/(w*r)}if(!bac)return;const hours=(bac/0.015).toFixed(1);const soberTime=new Date(Date.now()+hours*3600000);document.getElementById('result').innerHTML='<div class="result"><div class="value">'+hours+' hours</div><div class="label">Estimated Time to BAC 0.00%</div></div><div class="result-grid"><div class="result-card"><div class="num">'+soberTime.toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})+'</div><div class="lbl">Sober By</div></div><div class="result-card"><div class="num">'+bac.toFixed(3)+'%</div><div class="lbl">Starting BAC</div></div></div><div class="info-box">The body eliminates alcohol at ~0.015% BAC per hour. This is an estimate — actual elimination varies by metabolism, food intake, and other factors.</div>'}\`,
'pregnancy-weight-gain': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Pre-Pregnancy Weight (lbs)</label><input type="number" id="weight" placeholder="e.g. 140"></div><div><label>Height (inches)</label><input type="number" id="height" placeholder="e.g. 65"></div></div><div class="row"><div><label>Current Week of Pregnancy</label><input type="number" id="week" placeholder="e.g. 20" min="1" max="42"></div><div><label>Current Weight (lbs)</label><input type="number" id="current" placeholder="e.g. 150"></div></div><button onclick="calc()">Check Weight Gain</button><div id="result"></div>';function calc(){const w=+document.getElementById('weight').value;const h=+document.getElementById('height').value;const wk=+document.getElementById('week').value;const cur=+document.getElementById('current').value;if(!w||!h||!wk)return;const bmi=w/(h*h)*703;let rec;if(bmi<18.5)rec=[28,40];else if(bmi<25)rec=[25,35];else if(bmi<30)rec=[15,25];else rec=[11,20];const gained=cur?cur-w:0;const pct=wk/40;const expectedLow=Math.round(rec[0]*pct);const expectedHigh=Math.round(rec[1]*pct);let status;if(gained<expectedLow)status='Below recommended range';else if(gained<=expectedHigh)status='Within recommended range ✅';else status='Above recommended range';document.getElementById('result').innerHTML='<div class="result"><div class="value">'+rec[0]+'-'+rec[1]+' lbs</div><div class="label">Total Recommended Gain</div></div><div class="result-grid"><div class="result-card"><div class="num">'+gained+' lbs</div><div class="lbl">Gained So Far</div></div><div class="result-card"><div class="num">'+expectedLow+'-'+expectedHigh+' lbs</div><div class="lbl">Expected at Week '+wk+'</div></div><div class="result-card"><div class="num">'+bmi.toFixed(1)+'</div><div class="lbl">Pre-Pregnancy BMI</div></div></div><div class="info-box">'+status+'</div>'}\`,
'blood-pressure-checker': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Systolic (top number)</label><input type="number" id="sys" placeholder="e.g. 120" min="60" max="250"></div><div><label>Diastolic (bottom number)</label><input type="number" id="dia" placeholder="e.g. 80" min="40" max="150"></div></div><button onclick="calc()">Check Blood Pressure</button><div id="result"></div>';function calc(){const sys=+document.getElementById('sys').value;const dia=+document.getElementById('dia').value;if(!sys||!dia)return;let cat,col,advice;if(sys<120&&dia<80){cat='Normal';col='var(--accent)';advice='Your blood pressure is in the healthy range. Maintain a healthy lifestyle.'}else if(sys<130&&dia<80){cat='Elevated';col='var(--warn)';advice='You are at risk of developing high blood pressure. Improve diet and exercise.'}else if(sys<140||dia<90){cat='High Blood Pressure Stage 1';col='#f97316';advice='Consult your doctor. Lifestyle changes and possibly medication may be needed.'}else if(sys<180||dia<120){cat='High Blood Pressure Stage 2';col='var(--danger)';advice='See your doctor. You will likely need medication and lifestyle changes.'}else{cat='HYPERTENSIVE CRISIS';col='var(--danger)';advice='⚠️ SEEK EMERGENCY MEDICAL CARE IMMEDIATELY if you experience symptoms.'}document.getElementById('result').innerHTML='<div class="result"><div class="value" style="-webkit-text-fill-color:'+col+'">'+sys+'/'+dia+'</div><div class="label">'+cat+'</div></div><div class="info-box">'+advice+'</div>'}\`,
'a1c-calculator': \`const c=document.getElementById('calc');c.innerHTML='<label>Convert From:</label><select id="mode" onchange="toggle()"><option value="a1c">A1C → Average Blood Sugar</option><option value="bs">Blood Sugar → A1C</option></select><div id="input1"><label>A1C (%)</label><input type="number" id="a1c" placeholder="e.g. 7.0" step="0.1" min="4" max="15"></div><div id="input2" style="display:none"><label>Average Blood Sugar (mg/dL)</label><input type="number" id="bs" placeholder="e.g. 154" min="60" max="400"></div><button onclick="calc()">Convert</button><div id="result"></div>';function toggle(){const m=document.getElementById('mode').value;document.getElementById('input1').style.display=m==='a1c'?'block':'none';document.getElementById('input2').style.display=m==='bs'?'block':'none'}function calc(){const mode=document.getElementById('mode').value;let a1c,eag;if(mode==='a1c'){a1c=+document.getElementById('a1c').value;if(!a1c)return;eag=Math.round(28.7*a1c-46.7)}else{eag=+document.getElementById('bs').value;if(!eag)return;a1c=((eag+46.7)/28.7).toFixed(1)}let cat,col;if(a1c<5.7){cat='Normal';col='var(--accent)'}else if(a1c<6.5){cat='Prediabetes';col='var(--warn)'}else{cat='Diabetes Range';col='var(--danger)'}document.getElementById('result').innerHTML='<div class="result-grid"><div class="result-card"><div class="num" style="color:'+col+'">'+a1c+'%</div><div class="lbl">A1C</div></div><div class="result-card"><div class="num">'+eag+' mg/dL</div><div class="lbl">Avg Blood Sugar (eAG)</div></div></div><div class="result"><div class="label" style="color:'+col+'">'+cat+'</div></div><div class="info-box"><strong>A1C Ranges:</strong><br>Below 5.7% — Normal<br>5.7% to 6.4% — Prediabetes<br>6.5% or higher — Diabetes</div>'}\`,
'disability-insurance': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Monthly Income ($)</label><input type="number" id="income" placeholder="e.g. 6000"></div><div><label>Monthly Expenses ($)</label><input type="number" id="expenses" placeholder="e.g. 4000"></div></div><div class="row"><div><label>Emergency Fund (months)</label><input type="number" id="efund" value="3" min="0" max="24"></div><div><label>Existing Coverage ($)</label><input type="number" id="existing" value="0"></div></div><button onclick="calc()">Calculate Coverage Needed</button><div id="result"></div>';function calc(){const inc=+document.getElementById('income').value||0;const exp=+document.getElementById('expenses').value||0;const ef=+document.getElementById('efund').value||0;const exist=+document.getElementById('existing').value||0;const need=Math.round(inc*0.6);const gap=Math.max(0,need-exist);const fmt=n=>'$'+n.toLocaleString();document.getElementById('result').innerHTML='<div class="result"><div class="value">'+fmt(gap)+'/mo</div><div class="label">Coverage Gap to Fill</div></div><div class="result-grid"><div class="result-card"><div class="num">'+fmt(need)+'</div><div class="lbl">60% Income Target</div></div><div class="result-card"><div class="num">'+fmt(exist)+'</div><div class="lbl">Existing Coverage</div></div><div class="result-card"><div class="num">'+ef+' months</div><div class="lbl">Emergency Buffer</div></div></div><div class="info-box">Most disability policies replace 60% of income. Short-term policies cover 3-6 months; long-term policies cover until age 65. Benefits are typically tax-free if you pay premiums with after-tax dollars.</div>'}\`,
'waist-hip-ratio': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Waist (inches)</label><input type="number" id="waist" placeholder="At narrowest" step="0.5"></div><div><label>Hip (inches)</label><input type="number" id="hip" placeholder="At widest" step="0.5"></div></div><label>Gender</label><select id="gender"><option value="male">Male</option><option value="female">Female</option></select><button onclick="calc()">Calculate WHR</button><div id="result"></div>';function calc(){const w=+document.getElementById('waist').value;const h=+document.getElementById('hip').value;const g=document.getElementById('gender').value;if(!w||!h)return;const whr=(w/h).toFixed(2);let risk,col;if(g==='male'){if(whr<0.9){risk='Low Risk';col='var(--accent)'}else if(whr<1.0){risk='Moderate Risk';col='var(--warn)'}else{risk='High Risk';col='var(--danger)'}}else{if(whr<0.8){risk='Low Risk';col='var(--accent)'}else if(whr<0.85){risk='Moderate Risk';col='var(--warn)'}else{risk='High Risk';col='var(--danger)'}}document.getElementById('result').innerHTML='<div class="result"><div class="value" style="-webkit-text-fill-color:'+col+'">'+whr+'</div><div class="label">'+risk+'</div></div><div class="info-box"><strong>WHO Guidelines:</strong><br>Men: Below 0.90 (low risk), 0.90-0.99 (moderate), 1.0+ (high)<br>Women: Below 0.80 (low risk), 0.80-0.84 (moderate), 0.85+ (high)</div>'}\`,
'smoking-cost': \`const c=document.getElementById('calc');c.innerHTML='<div class="row"><div><label>Cigarettes Per Day</label><input type="number" id="cigs" placeholder="e.g. 10" min="1"></div><div><label>Price Per Pack ($)</label><input type="number" id="price" placeholder="e.g. 8.00" step="0.25" min="1"></div></div><div class="row"><div><label>Cigs Per Pack</label><input type="number" id="perpack" value="20"></div><div><label>Years Smoking</label><input type="number" id="years" placeholder="e.g. 5" min="0"></div></div><button onclick="calc()">Calculate Cost</button><div id="result"></div>';function calc(){const cigs=+document.getElementById('cigs').value;const price=+document.getElementById('price').value;const perPack=+document.getElementById('perpack').value||20;const years=+document.getElementById('years').value||0;if(!cigs||!price)return;const daily=cigs/perPack*price;const weekly=daily*7;const monthly=daily*30.44;const yearly=daily*365.25;const spent=yearly*years;const fmt=n=>'$'+n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});document.getElementById('result').innerHTML='<div class="result"><div class="value">'+fmt(yearly)+'</div><div class="label">Per Year</div></div><div class="result-grid"><div class="result-card"><div class="num">'+fmt(daily)+'</div><div class="lbl">Daily</div></div><div class="result-card"><div class="num">'+fmt(weekly)+'</div><div class="lbl">Weekly</div></div><div class="result-card"><div class="num">'+fmt(monthly)+'</div><div class="lbl">Monthly</div></div></div>'+(years?'<div class="danger-box">💸 Over '+years+' years, you\\'ve spent approximately <strong>'+fmt(spent)+'</strong> on cigarettes.'+(spent>10000?' That could have been a '+fmt(spent)+' investment portfolio!':'')+'</div>':'')+'<div class="info-box"><strong>If you quit and invested '+fmt(monthly)+'/month at 7% annual return:</strong><br>• 5 years: '+fmt(monthly*12*5*1.19)+'<br>• 10 years: '+fmt(monthly*12*10*1.42)+'<br>• 20 years: '+fmt(monthly*12*20*2.0)+'</div>'}\`,
  };
  return scripts[calc.slug] || simpleCalcs[calc.slug] || \`document.getElementById('calc').innerHTML='<p style="color:var(--muted)">Calculator coming soon...</p>';\`;
}

// Generate index page
function generateIndex() {
  const grouped = {};
  calcs.forEach(c => { if (!grouped[c.category]) grouped[c.category] = []; grouped[c.category].push(c); });
  const catEmoji = { Body: '🏋️', Diet: '🥗', 'Women\\'s Health': '👩', Wellness: '💊', Fitness: '🏃', Insurance: '🛡️' };
  
  return \`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>\${SITE_NAME} — Free Health & Wellness Calculators</title>
<meta name="description" content="Free health calculators: BMI, calorie counter, body fat, pregnancy due date, heart rate zones, insurance estimators, and more. No signup required.">
<meta name="keywords" content="health calculator, bmi calculator, calorie calculator, body fat calculator, pregnancy calculator, fitness calculator">
<link rel="canonical" href="\${SITE_URL}/">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=\${ADSENSE_ID}" crossorigin="anonymous"></script>
<style>
*{margin:0;padding:0;box-sizing:border-box}:root{--bg:#0c1222;--surface:#162032;--border:#1e3a5f;--text:#e2e8f0;--muted:#8899aa;--accent:#10b981;--accent2:#06b6d4}body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:var(--bg);color:var(--text);line-height:1.6}.container{max-width:1100px;margin:0 auto;padding:20px}header{text-align:center;padding:50px 0 30px}header h1{font-size:2.5em;margin-bottom:10px;background:linear-gradient(135deg,var(--accent),var(--accent2));-webkit-background-clip:text;-webkit-text-fill-color:transparent}header p{color:var(--muted);font-size:1.2em;max-width:600px;margin:0 auto}.search{max-width:500px;margin:20px auto}.search input{width:100%;padding:14px 20px;background:var(--surface);border:1px solid var(--border);border-radius:30px;color:var(--text);font-size:16px}.category{margin:32px 0}.category h2{color:var(--accent);font-size:1.3em;margin-bottom:16px;padding-left:8px;border-left:3px solid var(--accent)}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:16px}.card{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:20px;text-decoration:none;color:var(--text);transition:all .2s}.card:hover{border-color:var(--accent);transform:translateY(-3px);box-shadow:0 8px 25px rgba(16,185,129,0.15)}.card h3{font-size:1.05em;margin-bottom:6px}.card p{color:var(--muted);font-size:0.85em}.ad-slot{margin:20px 0;min-height:90px;text-align:center}.sites{text-align:center;padding:30px 0;background:var(--surface);border-radius:12px;margin:30px 0}.sites a{color:var(--accent);text-decoration:none;margin:0 12px;font-size:0.95em}footer{text-align:center;padding:40px 0;color:var(--muted);border-top:1px solid var(--border);margin-top:40px}footer a{color:var(--accent);text-decoration:none}@media(max-width:600px){header h1{font-size:1.8em}.grid{grid-template-columns:1fr}}
</style>
</head>
<body>
<div class="container">
<header><h1>🏥 \${SITE_NAME}</h1><p>Free health & wellness calculators. BMI, calories, body fat, pregnancy, fitness, insurance, and more.</p></header>
<div class="search"><input type="text" id="search" placeholder="🔍 Search calculators..." oninput="filterTools()"></div>
<div class="ad-slot"><ins class="adsbygoogle" style="display:block" data-ad-client="\${ADSENSE_ID}" data-ad-slot="auto" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div>
\${Object.entries(grouped).map(([cat, items]) => '<div class="category" data-cat="'+cat+'"><h2>'+(catEmoji[cat]||'📊')+' '+cat+'</h2><div class="grid">'+items.map(t => '<a href="'+t.slug+'.html" class="card" data-name="'+t.title.toLowerCase()+'"><h3>'+t.title+'</h3><p>'+t.desc.substring(0,90)+'...</p></a>').join('')+'</div></div>').join('')}
<div class="ad-slot"><ins class="adsbygoogle" style="display:block" data-ad-client="\${ADSENSE_ID}" data-ad-slot="auto" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div>
<div class="sites"><p style="color:var(--muted);margin-bottom:8px">More Free Tools:</p><a href="https://alexchalu.github.io/toolpulse/">🔧 ToolPulse — Dev Tools</a><a href="https://alexchalu.github.io/smartcalc/">🧮 SmartCalc — Finance</a><a href="https://alexchalu.github.io/writefast/">✍️ WriteFast — Writing Tools</a></div>
<footer><p>\${SITE_NAME} — Free Health & Wellness Calculators</p><p style="margin-top:8px">⚠️ For informational purposes only. Always consult a healthcare professional.</p></footer>
</div>
<script>function filterTools(){const q=document.getElementById('search').value.toLowerCase();document.querySelectorAll('.card').forEach(c=>{c.style.display=c.dataset.name.includes(q)?'':'none'});document.querySelectorAll('.category').forEach(cat=>{const visible=cat.querySelectorAll('.card[style=""], .card:not([style])');cat.style.display=visible.length===0&&q?'none':''})}</script>
</body>
</html>\`;
}

// Generate sitemap
function generateSitemap() {
  const urls = [SITE_URL + '/'];
  calcs.forEach(c => urls.push(SITE_URL + '/' + c.slug + '.html'));
  return '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(u=>'<url><loc>'+u+'</loc><changefreq>weekly</changefreq><priority>'+(u.endsWith('/')?'1.0':'0.8')+'</priority></url>').join('')+'</urlset>';
}

// BUILD
console.log('Building ' + SITE_NAME + '...');
fs.writeFileSync('index.html', generateIndex());
console.log('✅ index.html');
calcs.forEach(c => { fs.writeFileSync(c.slug + '.html', generateCalcPage(c)); console.log('✅ ' + c.slug + '.html'); });
fs.writeFileSync('sitemap.xml', generateSitemap());
console.log('✅ sitemap.xml');
fs.writeFileSync('robots.txt', 'User-agent: *\\nAllow: /\\nSitemap: '+SITE_URL+'/sitemap.xml');
console.log('✅ robots.txt');
fs.writeFileSync('a1b2c3d4e5f6g7h8.txt', 'a1b2c3d4e5f6g7h8');
console.log('✅ IndexNow key');
console.log('\\n🎉 Built ' + calcs.length + ' health calculators + index + sitemap');
